//! API Protocol Types
//!
//! This module contains types used for API protocol communication (over-the-wire).

use crate::types::trading::Side;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
pub struct Timestamp {
    pub ts: i32,
    pub tn: u32,
}

impl Timestamp {
    pub fn now() -> Self {
        let now = Utc::now();
        now.into()
    }

    pub fn as_datetime(&self) -> Option<DateTime<Utc>> {
        DateTime::from_timestamp(self.ts as i64, self.tn)
    }

    /// Nanoseconds since the Unix epoch. A pre-epoch timestamp clamps to 0.
    pub fn epoch_ns(&self) -> u64 {
        u64::try_from(self.ts).unwrap_or(0) * 1_000_000_000 + self.tn as u64
    }
}

impl From<DateTime<Utc>> for Timestamp {
    fn from(value: DateTime<Utc>) -> Self {
        Self {
            ts: value.timestamp() as i32,
            tn: value.timestamp_subsec_nanos(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
pub struct Fill {
    pub trade_id: String,
    pub order_id: Option<String>,
    pub account_id: String,
    pub timestamp: DateTime<Utc>,
    pub symbol: String,
    pub price: Decimal,
    pub quantity: u64,
    pub is_taker: bool,
    pub fee: Decimal,
    pub side: Side,
    pub realized_pnl: Option<Decimal>,
    /// True if this fill was generated by a block trade — a privately
    /// negotiated trade booked away from the order book.
    #[serde(default, skip_serializing_if = "is_false")]
    pub is_block_trade: bool,
    /// True if this fill was generated by final settlement of a delisted or
    /// expired contract at the final settlement price; the counterparty is the
    /// exchange settlement account. Implies `is_block_trade`.
    #[serde(default, skip_serializing_if = "is_false")]
    pub is_final_settlement: bool,
}

fn is_false(b: &bool) -> bool {
    !b
}
